# Generated by Django 4.1.4 on 2023-03-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_customer_address_line_1_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
