# Generated by Django 4.1.4 on 2023-03-31 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_stripe_price_product_stripe_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_price',
        ),
    ]
