# Generated by Django 4.1.4 on 2023-03-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_stripe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price',
            field=models.IntegerField(default=1000),
        ),
    ]
