# Generated by Django 4.1.7 on 2023-04-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_orderitem_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_code_number',
            new_name='product_code',
        ),
    ]
